package expo.modules.tormanager

import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/** B.2d-4 Task 1 -- KotlinSeal: anonymous per-recipient mutual-box slots
 *  (sealSlots/tryOpenSlots), Kotlin port of hearth.dmcrypt.seal_slots /
 *  try_open_slots. Byte-matches the Python via the same X25519 + HKDF +
 *  ChaCha20-Poly1305 construction KotlinDmcrypt already proved out. */
class KotlinSealTest {
    @Test fun sealSlotsOpenRoundTripAndStrangerAndBucket() {
        fun kp() = org.bouncycastle.crypto.params.X25519PrivateKeyParameters(java.security.SecureRandom())
        val a = kp(); val b = kp(); val stranger = kp()
        val aPubHex = KotlinWire.toHex(a.generatePublicKey().encoded)
        val bPubHex = KotlinWire.toHex(b.generatePublicKey().encoded)
        val payload = "hi".repeat(20).toByteArray()
        val slots = KotlinSeal.sealSlots(payload, listOf(aPubHex, bPubHex))
        assertEquals("padded to first bucket >= 2", 8, slots.size)   // _SLOT_BUCKETS
        // a recipient recovers the payload; a stranger does not
        assertArrayEquals(payload, KotlinSeal.tryOpenSlots(slots, KotlinWire.toHex(a.encoded)))
        assertArrayEquals(payload, KotlinSeal.tryOpenSlots(slots, KotlinWire.toHex(b.encoded)))
        assertNull(KotlinSeal.tryOpenSlots(slots, KotlinWire.toHex(stranger.encoded)))
        // malformed enc_pub skipped, not thrown
        assertEquals(8, KotlinSeal.sealSlots(payload, listOf(aPubHex, "zz")).size)
    }

    @Test fun sealSlotsBucketsGrow() {
        val payload = "x".toByteArray()
        val pubs = (0 until 9).map { KotlinWire.toHex(
            org.bouncycastle.crypto.params.X25519PrivateKeyParameters(java.security.SecureRandom()).generatePublicKey().encoded) }
        assertEquals("9 real -> bucket 16", 16, KotlinSeal.sealSlots(payload, pubs).size)
    }

    /** Review fix (B.2d-4 Task 1): the two tests above only prove KotlinSeal
     *  is self-consistent (Kotlin-sealed, Kotlin-opened) -- a systematic
     *  error applied identically on both sides (wrong HKDF info, wrong AAD)
     *  would still pass them. This test opens slots genuinely sealed by
     *  hearth.dmcrypt.seal_slots (fixtures/seal_vector.json, generated by a
     *  one-off script and round-tripped through hearth's own
     *  try_open_slots before being written out), pinning tryOpenSlots'
     *  X25519 agreement + HKDF info + AAD byte-for-byte against Python. */
    @Test fun tryOpenSlotsOpensAHearthSealedVector() {
        val t = javaClass.classLoader!!.getResourceAsStream("seal_vector.json")!!
            .readBytes().toString(Charsets.UTF_8)
        val v = JSONObject(t)
        val slotsJson = v.getJSONArray("slots")
        val slots = (0 until slotsJson.length()).map { i ->
            val s = slotsJson.getJSONObject(i)
            mapOf("eph_pub" to s.getString("eph_pub"),
                  "nonce" to s.getString("nonce"),
                  "ct" to s.getString("ct"))
        }
        val expected = v.getString("payload_utf8").toByteArray(Charsets.UTF_8)
        assertArrayEquals(expected, KotlinSeal.tryOpenSlots(slots, v.getString("enc_priv")))
        // a wrong key must not open any slot (Python-sealed, Kotlin-opened direction)
        assertNull(KotlinSeal.tryOpenSlots(slots, "11".repeat(32)))
    }
}
